version: '2'

services:
    remark42:
        image: umputun/remark42:latest
        restart: always
        container_name: "remark42"

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
            - "8080:8080"    #VERY IMPORTANT : DO NOT CHANGE THIS.

        environment:
            - REMARK_URL=https://www.remark42.yoursite.com  # url pointing to your remark42 server
            - SITE=remark42.yoursite                     # site ID, same as used for `site_id`, see "Setup on your website"
            - SECRET=somesecrethere        # secret key
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - AUTH_GITHUB_CID=somegithubappcid # oauth2 client ID     
            - AUTH_GITHUB_CSEC=somegithubappsecret   # oauth2 client secret
            - AUTH_GOOGLE_CID=somegooglecappid  # oauth2 client ID     
            - AUTH_GOOGLE_CSEC=somegoogleappsecret # oauth2 client secret
            - AUTH_EMAIL_ENABLE=true
            - AUTH_EMAIL_HOST=smtp.mailgun.org  #This example uses mailgun configuration below
            - AUTH_EMAIL_PORT=465 
            - AUTH_EMAIL_FROM=noreply@mail.yoursite.com
            - AUTH_EMAIL_SUBJ=remark42 confirmation
            - AUTH_EMAIL_CONTENT_TYPE=text/html
            - AUTH_EMAIL_TLS=true
            - AUTH_EMAIL_USER=postmaster@mail.yoursite.com
            - AUTH_EMAIL_PASSWD=mailgunpassword 
            - AUTH_EMAIL_TIMEOUT=10s
        volumes:
            - ./var:/srv/var                        # persistent volume to store all remark42 data
